#ifndef LIBOSMSCOUT_IMPORT_FEATURES
#define LIBOSMSCOUT_IMPORT_FEATURES

#ifndef OSMSCOUT_IMPORT_HAVE_LIB_MARISA
/* libmarisa is available */
#cmakedefine OSMSCOUT_IMPORT_HAVE_LIB_MARISA
#endif

#endif