osmscoutclientSrc = [
             'src/osmscoutclient/AvailableMapEntry.cpp',
             'src/osmscoutclient/DBInstance.cpp',
             'src/osmscoutclient/DBJob.cpp',
             'src/osmscoutclient/DBThread.cpp',
             'src/osmscoutclient/FavoriteLocationService.cpp',
             'src/osmscoutclient/MapDirectory.cpp',
             'src/osmscoutclient/MapDownloadService.cpp',
             'src/osmscoutclient/MapManager.cpp',
             'src/osmscoutclient/MapProvider.cpp',
             'src/osmscoutclient/OnlineTileProvider.cpp',
             'src/osmscoutclient/POILookupModule.cpp',
             'src/osmscoutclient/Settings.cpp',
             'src/osmscoutclient/VoiceProvider.cpp'
          ]
