version: 2
jobs:
  build:
    docker:
      - image: libosmscout/archlinux_gcc_cmake:latest
        environment:
          TZ: "/usr/share/zoneinfo/Europe/Berlin"
          LANG: "en_US.utf8"
    branches:
      only:
        - master
        - pull/*
    steps:
      - checkout
      - run:
          name: Configure project
          command: cmake -B build -DCMAKE_UNITY_BUILD=ON -DOSMSCOUT_BUILD_BINDING_JAVA=OFF -Wno-dev
      - run:
          name: Build project
          command: cmake --build build
      - run:
          name: Test project
          command: ctest -j 2 --output-on-failure
          working_directory: build

