osmscoutclientjavaJniHeaders = javaModule.native_headers(
  'com/framstag/libosmscout/client/AvailableMapEntry.java',
  'com/framstag/libosmscout/client/DescriptionEntry.java',
  'com/framstag/libosmscout/client/FavoriteLocation.java',
  'com/framstag/libosmscout/client/FavoriteLocationGroup.java',
  'com/framstag/libosmscout/client/LaneTurn.java',
  'com/framstag/libosmscout/client/MapDownloadListener.java',
  'com/framstag/libosmscout/client/MapDownloadManager.java',
  'com/framstag/libosmscout/client/MapProvider.java',
  'com/framstag/libosmscout/client/NavigationController.java',
  'com/framstag/libosmscout/client/NavigationListener.java',
  'com/framstag/libosmscout/client/NavigationPosition.java',
  'com/framstag/libosmscout/client/NavigationState.java',
  'com/framstag/libosmscout/client/ObjectDescription.java',
  'com/framstag/libosmscout/client/OSMScoutClient.java',
  'com/framstag/libosmscout/client/OSMScoutClientBuilder.java',
  'com/framstag/libosmscout/client/LocationEntry.java',
  'com/framstag/libosmscout/client/RouteEntry.java',
  'com/framstag/libosmscout/client/RouteCallback.java',
  'com/framstag/libosmscout/client/RouteInstruction.java',
  'com/framstag/libosmscout/client/RoutingProfile.java',
  'com/framstag/libosmscout/client/TrackPoint.java',
  'com/framstag/libosmscout/client/TurnType.java',
  'com/framstag/libosmscout/client/Vehicle.java',
  package: 'com.framstag.libosmscout.client',
  classes: ['OSMScoutClient', 'OSMScoutClientBuilder', 'LocationEntry', 'RouteEntry', 'NavigationController', 'MapDownloadManager']
)

osmscoutclientjavaJniIncDir = include_directories('.')

osmscoutclientjavaJar = jar(
  'libosmscoutclientjava',
  'com/framstag/libosmscout/client/AvailableMapEntry.java',
  'com/framstag/libosmscout/client/DescriptionEntry.java',
  'com/framstag/libosmscout/client/FavoriteLocation.java',
  'com/framstag/libosmscout/client/FavoriteLocationGroup.java',
  'com/framstag/libosmscout/client/LaneTurn.java',
  'com/framstag/libosmscout/client/MapDownloadListener.java',
  'com/framstag/libosmscout/client/MapDownloadManager.java',
  'com/framstag/libosmscout/client/MapProvider.java',
  'com/framstag/libosmscout/client/NavigationController.java',
  'com/framstag/libosmscout/client/NavigationListener.java',
  'com/framstag/libosmscout/client/NavigationPosition.java',
  'com/framstag/libosmscout/client/NavigationState.java',
  'com/framstag/libosmscout/client/ObjectDescription.java',
  'com/framstag/libosmscout/client/OSMScoutClient.java',
  'com/framstag/libosmscout/client/OSMScoutClientBuilder.java',
  'com/framstag/libosmscout/client/LocationEntry.java',
  'com/framstag/libosmscout/client/RouteEntry.java',
  'com/framstag/libosmscout/client/RouteCallback.java',
  'com/framstag/libosmscout/client/RouteInstruction.java',
  'com/framstag/libosmscout/client/RoutingProfile.java',
  'com/framstag/libosmscout/client/TrackPoint.java',
  'com/framstag/libosmscout/client/TurnType.java',
  'com/framstag/libosmscout/client/Vehicle.java',
)