#ifndef LIBOSMSCOUT_MAP_OPENGL_FEATURES
#define LIBOSMSCOUT_MAP_OPENGL_FEATURES

#ifndef SHADER_INSTALL_DIR
#cmakedefine SHADER_INSTALL_DIR "${SHADER_INSTALL_DIR}"
#endif

#ifndef DEFAULT_FONT_FILE
#cmakedefine DEFAULT_FONT_FILE "${DEFAULT_FONT_FILE}"
#endif

#endif
