#!/bin/sh
# mapgen-entrypoint.sh - decide how the container runs.
#
#   1. with arguments: run the pass with those arguments and exit, whatever else
#      is configured. This is how --check-config and --help work, and how an
#      explicit single run is asked for.
#   2. MAPGEN_CRON unset: one pass, then exit. The container is a job for an
#      external scheduler.
#   3. MAPGEN_CRON set: run the pass on that schedule until the container is
#      stopped. The container is a service.
#
# The scheduler is supercronic, which needs no privileges and no writable root
# filesystem, validates the crontab while starting, and does not start a job
# again while its previous run is still going.
#
# Environment:
#   MAPGEN_CRON      cron expression for the scheduled mode (unset: one pass)
#   MAPGEN_WORK_DIR  transient work area (default: /work); holds the crontab
#   TZ               time zone the expression is evaluated in
#
# Usage:
#   mapgen-entrypoint.sh [arguments of mapgen.sh]

set -eu

WORK_DIR="${MAPGEN_WORK_DIR:-/work}"
CRONTAB="${WORK_DIR}/mapgen.crontab"

if [ "$#" -gt 0 ]; then
  exec /usr/local/bin/mapgen.sh "$@"
fi

if [ -z "${MAPGEN_CRON:-}" ]; then
  exec /usr/local/bin/mapgen-pass.sh
fi

# Generated rather than mounted: the schedule is configuration of the service,
# not a second file to keep in step with it.
cat > "${CRONTAB}" <<EOF
# Generated by mapgen-entrypoint.sh from MAPGEN_CRON. Do not edit.
${MAPGEN_CRON} /usr/local/bin/mapgen-pass.sh
EOF

echo "[mapgen] running the pass on the schedule '${MAPGEN_CRON}' (time zone ${TZ:-UTC})"

exec /usr/local/bin/supercronic "${CRONTAB}"
