#!/bin/sh
# mapgen-entrypoint.sh - decide how the container runs.
#
#   1. with arguments: run the pass with those arguments and exit, whatever else
#      is configured. This is how --check-config and --help work, and how an
#      explicit single run is asked for.
#   2. MAPGEN_CRON unset: one pass, then exit. The container is a job for an
#      external scheduler.
#   3. MAPGEN_CRON set: run the pass on that schedule until the container is
#      stopped. The container is a service.
#
# The scheduler is supercronic, which needs no privileges and no writable root
# filesystem, validates the crontab while starting, and does not start a job
# again while its previous run is still going.
#
# Environment:
#   MAPGEN_CRON      cron expression for the scheduled mode (unset: one pass)
#   MAPGEN_WORK_DIR  transient work area (default: /work); holds the crontab
#   MAPGEN_REPO_DIR  database repository (default: /repository)
#   TZ               time zone the expression is evaluated in
#
# Both areas must be writable by the identity the container runs as; the entry
# point reports an area that is not, with the command that fixes it.
#
# Usage:
#   mapgen-entrypoint.sh [arguments of mapgen.sh]

set -eu

WORK_DIR="${MAPGEN_WORK_DIR:-/work}"
REPO_DIR="${MAPGEN_REPO_DIR:-/repository}"
CRONTAB="${WORK_DIR}/mapgen.crontab"

if [ "$#" -gt 0 ]; then
  # Arguments ask for one run with those arguments (--check-config, --help, an
  # explicit pass). They only read, so no writability is required.
  exec /usr/local/bin/mapgen.sh "$@"
fi

# Both modes write into the mounted areas: the pass downloads into the work
# area and places databases in the repository, and the scheduled mode also
# keeps its crontab in the work area. Docker creates a named volume owned by
# root, while the process runs as the image's non-root identity, so an unseeded
# volume fails at the first write - report that here, with the identity and the
# command that fixes it, instead of failing later and less legibly.
require_writable() {
  area="$1"
  description="$2"
  probe="${area}/.mapgen-write-check"

  if touch "${probe}" 2>/dev/null; then
    rm -f "${probe}"
    return 0
  fi

  echo "[mapgen] ${description} (${area}) is not writable by uid $(id -u), gid $(id -g)." >&2
  echo "[mapgen] A volume created by Docker belongs to root; give the mounted areas" >&2
  echo "[mapgen] that identity once, for example:" >&2
  echo "[mapgen]   docker compose -f <compose file> run --rm --user root --entrypoint sh mapgen \\" >&2
  echo "[mapgen]     -c 'chown -R $(id -u):$(id -g) /work /repository'" >&2
  echo "[mapgen] or set PUID/PGID to the ids that own the mount. See" >&2
  echo "[mapgen] Documentation/MapRepository.md, section 5." >&2
  exit 1
}

require_writable "${WORK_DIR}" "the work area"
require_writable "${REPO_DIR}" "the repository"

if [ -z "${MAPGEN_CRON:-}" ]; then
  exec /usr/local/bin/mapgen-pass.sh
fi

# Generated rather than mounted: the schedule is configuration of the service,
# not a second file to keep in step with it.
cat > "${CRONTAB}" <<EOF
# Generated by mapgen-entrypoint.sh from MAPGEN_CRON. Do not edit.
${MAPGEN_CRON} /usr/local/bin/mapgen-pass.sh
EOF

echo "[mapgen] running the pass on the schedule '${MAPGEN_CRON}' (time zone ${TZ:-UTC})"

exec /usr/local/bin/supercronic "${CRONTAB}"
