name: iOS

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_cmake:
    name: cmake
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build tool
        run:  brew install cmake ninja
      - name: Install dependencies
        run: brew install openjdk protobuf protobuf-c qt5 cairo libxml2 gettext pango glfw3 glew glm pkgconfig
      - name: Configure build project
        run: cmake -B build -DCMAKE_TOOLCHAIN_FILE=../cmake/iOS.cmake -DPKG_CONFIG_EXECUTABLE=/usr/local/bin/pkg-config -DCMAKE_UNITY_BUILD=ON -Wno-dev
      - name: Build project
        run: cmake --build build
