name: Windows using Visual Studio 2019 and meson

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master


jobs:
  build:
    name: Windows+Visual_Studio+meson - Build and test
    runs-on: windows-2019
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.x for meson
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install meson and ninja
        run:  pip install meson ninja
      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64
      - name: Dump environment
        run:  set
      - name: Configure build project
        run:  meson setup --buildtype debugoptimized --wrap-mode nofallback --unity on build
      - name: Build project
        run:  meson compile -C build
      - name: Test project
        run:  meson test -C build --print-errorlogs


