name: Build and test on ubuntu 18.04 using gcc and meson
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure build project
        run: meson setup debug
      - name: Build project
        run: ninja -C debug
      - name: Run tests
        run: meson test -C debug
