name: MSYS using gcc and meson

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and test
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSYS/MINGW64
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: "mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool mingw-w64-x86_64-libiconv
                    mingw-w64-x86_64-meson mingw-w64-x86_64-ninja
                    mingw-w64-x86_64-protobuf
                    mingw-w64-x86_64-libxml2
                    mingw-w64-x86_64-cairo mingw-w64-x86_64-pango
                    mingw-w64-x86_64-qt5
                    mingw-w64-x86_64-glew mingw-w64-x86_64-glfw mingw-w64-x86_64-glm"
      - name: Configure build project
        run: meson setup --buildtype debugoptimized --unity on debug
        env:
          CXX: ccache g++
          CC: ccache gcc
      - name: Build project
        run: ninja -C debug
#      - name: Run tests
#        run: meson test -C debug
#        env:
#          LANG: en_US.utf8
