name: Ubuntu 18.04 using gcc and meson

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Ubuntu+gcc+meson - Build and test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install software-properties-common
        run:  sudo apt-get install software-properties-common
      - name: Install libosmscout dependencies
        run:  "sudo apt-get update && sudo apt-get install -y
               libxml2-dev
               libprotobuf-dev protobuf-compiler
               libagg-dev
               libfreetype6-dev libcairo2-dev libpangocairo-1.0-0 libpango1.0-dev
               qt5-default qtdeclarative5-dev libqt5svg5-dev qtlocation5-dev qtpositioning5-dev qttools5-dev-tools
               qttools5-dev qtmultimedia5-dev
               freeglut3 freeglut3-dev
               libmarisa-dev"
      - name: Add Ubuntu Toolchain PPA
        run:  sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - name: Install gcc compiler and ninja
        run:  sudo apt-get -y install gcc-10 g++-10 ccache libtool pkg-config ninja-build
      - name: Add eoan repository to apt for current meson
        run:  sudo add-apt-repository -y -u "deb http://de.archive.ubuntu.com/ubuntu eoan main universe"
      - name: Install meson and libtbb-dev von eoan repository
        run:  sudo apt-get -y install meson libtbb-dev
      - name: Configure build project
        run:  meson setup debug
        env:
          CXX: ccache g++-10
          CC: ccache gcc-10
      - name: Build project
        run:  ninja -C debug
      - name: Run tests
        run:  meson test -C debug --print-errorlogs
