name: OS X and cmake

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: OSX+cmake - Build and test
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install build tool
        run:  brew install ninja
      - name: Configure build project
        run: cmake -B build -DCMAKE_UNITY_BUILD=ON -Wno-dev -G "Ninja"
      - name: Build project
        run: cmake --build build
