name: MSYS using gcc and cmake

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: MSYS+gcc+cmake - Build and test
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSYS/MINGW64
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: "mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool mingw-w64-x86_64-libiconv
                    mingw-w64-x86_64-cmake mingw-w64-x86_64-extra-cmake-modules make
                    mingw-w64-x86_64-protobuf
                    mingw-w64-x86_64-libxml2
                    mingw-w64-x86_64-cairo mingw-w64-x86_64-pango
                    mingw-w64-x86_64-qt5
                    mingw-w64-x86_64-glew mingw-w64-x86_64-glfw mingw-w64-x86_64-glm"
      - name: Configure build project
        run: cmake -B build -DCMAKE_UNITY_BUILD=ON -Wno-dev -G 'MSYS Makefiles'
      - name: Build project
        run: cmake --build build
      - name: Run tests
        run:  PATH=$PATH:$PWD/libosmscout:$PWD/libosmscout-import:$PWD/libosmscout-map:$PWD/libosmscout-test ctest -j 4 --output-on-failure
        working-directory: build
