name: MSYS using gcc and meson
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSYS/MINGW64 
        uses: numworks/setup-msys2@v1
      - name: Install gcc toolchain
        run: msys2do pacman -S --needed --noconfirm mingw-w64-x86_64-toolchain mingw-w64-x86_64-libtool mingw-w64-x86_64-libiconv
      - name: Install meson build tool
        run: msys2do pacman -S --needed --noconfirm mingw-w64-x86_64-meson mingw-w64-x86_64-ninja
      - name: Install libosmscout dependencies
        run: "msys2do pacman -S --needed --noconfirm --disable-download-timeout
              mingw-w64-x86_64-protobuf 
              mingw-w64-x86_64-libxml2
              mingw-w64-x86_64-cairo mingw-w64-x86_64-pango 
              mingw-w64-x86_64-qt5 
              mingw-w64-x86_64-glew mingw-w64-x86_64-glfw mingw-w64-x86_64-glm"
      - name: Flush pacman caches
        run: msys2do pacman -Scc --noconfirm
      - name: Configure build project
        run: msys2do meson setup debug
        env:
          CXX: ccache g++
          CC: ccache gcc
      - name: Build project
        run: msys2do ninja -C debug
#      - name: Run tests
#        run: msys2do meson test -C debug
#        env:
#          LANG: en_US.utf8
