name: Ubuntu 18.04 for Qt on Android

# See https://doc.qt.io/qt-5/android-getting-started.html
# See https://github.com/jurplel/install-qt-action
# See https://github.com/miurahr/aqtinstall/

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Run sdkmanager update
        run:  ${ANDROID_HOME}/tools/bin/sdkmanager --update
      - name: Install android platform, platform-tools, build-tools and ndk
        run:  ${ANDROID_HOME}/tools/bin/sdkmanager --install "platform-tools" "platforms;android-29" "build-tools;29.0.2" "ndk;21.3.6528147"
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v1
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          host: 'linux'
          target: 'android'
          arch: 'android_armv7'
          install-deps: 'true'
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
      - name: Configure build project
        run: "cmake -B build
                    -DCMAKE_TOOLCHAIN_FILE=${ANDROID_HOME}/ndk/21.3.6528147/build/cmake/android.toolchain.cmake
                    -DANDROID_NDK=${ANDROID_HOME}/ndk/21.3.6528147/
                    -DANDROID_ABI=armeabi-v7a
                    -DANDROID_PLATFORM=android-29
                    -DANDROID_STL=c++_shared
                    -DOSMSCOUT_BUILD_IMPORT=OFF
                    -DOSMSCOUT_BUILD_GPX=OFF
                    -DOSMSCOUT_BUILD_DEMOS=OFF
                    -DOSMSCOUT_BUILD_TOOL_DUMPDATA=OFF
                    -DOSMSCOUT_BUILD_DOC_API=OFF
                    -DOSMSCOUT_BUILD_WEBPAGE=OFF"
      - name: Build project
        run:  cmake --build build
