name: OS X

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/**'

jobs:
  build_meson:
    name: meson
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install build tool
        run: brew install meson ninja
      - name: Install dependencies
        run: brew install openjdk catch2 protobuf protobuf-c qt@5 cairo libxml2 gettext pango glfw glew glm pkgconfig
      - name: Configure build project
        run: meson setup --buildtype debugoptimized --unity on debug -Dopenmp=false
        env:
          PKG_CONFIG_PATH: "/usr/local/opt/qt@5/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig"
      - name: Build project
        run: meson compile -C debug
      - name: Execute tests
        run: meson test -C debug --print-errorlogs

  build_cmake:
    name: cmake
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install build tool
        run:  brew install cmake ninja
      - name: Install dependencies
        run: brew install openjdk catch2 protobuf protobuf-c qt@5 cairo libxml2 gettext pango glfw glew glm pkgconfig
      - name: Configure build project
        run: cmake -B build -DQt5_DIR=$(brew --prefix qt@5)/lib/cmake/Qt5 -DCMAKE_UNITY_BUILD=ON -Wno-dev -G "Ninja"
        env:
          PKG_CONFIG_PATH: "/usr/local/opt/qt@5/lib/pkgconfig:/usr/local/opt/libxml2/lib/pkgconfig"
      - name: Build project
        run: cmake --build build
      - name: Run tests
        run: ctest -j 2 --output-on-failure --exclude-regex PerformanceTest-opengl
        working-directory: build
