name: Release Latest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  create_latest_release:
    name: Create latest release
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install gcc compiler and Co
        run:  sudo apt-get -y install gcc-12 g++-12 libtbb-dev ccache libtool pkg-config

      - name: Install meson and ninja via pip
        run:  "pip install meson ninja"

      - name: Set version locally to 'latest'
        run:  |
          sed -i "s/^ *version: *'[0-9.]*', *$/        version: 'latest',/g" meson.build

      - name: Initialize meson project
        run:  meson setup dist --wrap-mode nofallback
        env:
          CXX: g++-12
          CC: gcc-12

      - name: Create distribution archive
        run:  meson dist -C dist --formats "xztar,zip" --no-tests --allow-dirty

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: JReleaser full-release
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_PROJECT_VERSION: ${{ latest }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: JReleaser upload output
        uses: actions/upload-artifact@v3
        with:
          name: jreleaser-release
          path: |
            out/jreleaser/trace.log
            out/jreleaser/output.properties
